services:
  immich-slideshow-old-devices:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: immich-slideshow-old-devices
    ports:
      - "8080:80"
    environment:
      - IMMICH_URL=${IMMICH_URL} # Required
      - IMMICH_API_KEY=${IMMICH_API_KEY} # Required
      - ALBUM_ID=${ALBUM_ID} # Required
      - CAROUSEL_DURATION=${CAROUSEL_DURATION:-5}
      - CSS_BACKGROUND_COLOR=${CSS_BACKGROUND_COLOR:-black}
      - RANDOM_ORDER=${RANDOM_ORDER:-false}
      - STATUS_BAR_STYLE=${STATUS_BAR_STYLE:-black-translucent}
      - IMAGES_ORIENTATION=${IMAGES_ORIENTATION:-all}
    volumes:
      - ./public:/var/www/html